version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  reviewers:
  - karelhala
  allow:
  - dependency-name: "@redhat-cloud-services/frontend*"
  - dependency-name: "@patternfly/*"
    dependency-type: direct
  ignore:
  - dependency-name: "@patternfly/patternfly"
    versions:
    - 4.102.1
    - 4.80.3
    - 4.87.2
    - 4.87.3
    - 4.90.5
    - 4.96.2
  - dependency-name: "@patternfly/react-table"
    versions:
    - 4.20.15
    - 4.23.0
    - 4.23.1
    - 4.23.14
    - 4.23.2
    - 4.24.0
    - 4.24.1
    - 4.26.6
  - dependency-name: "@patternfly/react-core"
    versions:
    - 4.101.3
    - 4.106.1
    - 4.106.2
    - 4.115.1
    - 4.90.2
    - 4.97.0
    - 4.97.1
    - 4.97.2
